# Generated by Django 3.0.5 on 2022-10-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminusers',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
